M12
Dani2525/Devops-Course-Starter pull request #12
Opened 2022-11-25 16:56 UTC by Dani2525

2022-12-05 16:33 UTC, CorndelWithSoftwireDevOps requested changes
Thanks for the submission. There are few things that need to be fixed, but the terraform implementation looks sound.

There are secrets in the version control. You will need to make sure those are managed in another way and make sure you don't check them in. I left a comment about fixing the issue in the git history; hopefully it comes in handy when remediating the previous times it happened.

Your `README.md` update is lacking some important information about how to set up and run terraform to deploy locally.

2022-12-05 16:33 UTC, CorndelDevOps commented on .env.j2
> -TRELLO_KEY=ea5ad9c0c898c165ba252befc3bd42cf
It looks like you committed some secrets in the past that you rightly deleted from version control - it happens.
One way to prevent them from being in the git history is interactively rebasing your git history to delete the commits they were introduced.
`git pull` in case there are any changes
`git rebase <last tag without secrets> -i` will give you an opportunity to 'fixup' some commits together.
`git push -f` will overwrite remote history of your branch, removing any references to secrets.

2022-12-05 16:33 UTC, CorndelDevOps commented on README.md
> +mongo_client=mongodb://module10:t0qwxU3V7MZ2Y55mhbnRAtefiGrwJTUHaTO6MhO0Kv8KTW3PX6GKvlon3LF1h8u29BCgQRYE41wgACDbSTzsgg==@module10.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrite
oops - you've got a secret looking values in this and following lines.

2022-12-05 16:33 UTC, CorndelDevOps commented on README.md
> +main.tf file uses declarative script to make Azure Infrastructure, where Todoapp is deployed to.
1. The markdown formatting of this is not what you'd expect.
2. This is not enough information for someone setting up the project to know what they need to do to run terraform. You will need to add some information about first time setup and how to run it, perhaps explain where to get the variable values if you think it's not obvious

2022-12-29 15:25 UTC, Dani2525 commented on README.md
> +mongo_client=mongodb://module10:t0qwxU3V7MZ2Y55mhbnRAtefiGrwJTUHaTO6MhO0Kv8KTW3PX6GKvlon3LF1h8u29BCgQRYE41wgACDbSTzsgg==@module10.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrite
removed :)

2023-01-05 13:10 UTC, Dani2525 commented on README.md
> +main.tf file uses declarative script to make Azure Infrastructure, where Todoapp is deployed to.
added more info on my readme

2023-01-09 14:38 UTC, CorndelWithSoftwireDevOps approved these changes
Thanks for the changes. Looks good!

2023-01-09 19:48 UTC, merged